import { Request, Response, NextFunction } from 'express';
import { z } from 'zod';
import crypto from 'crypto';
import bcrypt from 'bcrypt';
import multer from 'multer';
import { parse } from 'csv-parse/sync';
import { query, withTransaction } from '../../db/pool';
import { AppError } from '../../middleware/errorHandler';
import { logAudit } from '../../services/audit.service';
import { sendCredentials } from '../../services/email.service';
import { config } from '../../config';
import type { GraduateRow, FacultyRow, GateRow, EventRow, ImportSummary, GraduateCsvRow } from '../../types';

export const upload = multer({ storage: multer.memoryStorage(), limits: { fileSize: 10 * 1024 * 1024 } });

// ── PIN generation ────────────────────────────────────────────────────────────
// Produces a 17-char PIN in XXXXX-XXXXX-XXXXX format.
// Alphabet excludes visually confusable characters (0/O, 1/I/L).

const PIN_ALPHABET = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';

function generatePin(): string {
  const bytes = crypto.randomBytes(15);
  const chars = Array.from({ length: 15 }, (_, i) => PIN_ALPHABET[bytes[i]! % PIN_ALPHABET.length]!);
  return `${chars.slice(0, 5).join('')}-${chars.slice(5, 10).join('')}-${chars.slice(10, 15).join('')}`;
}

// ── CSV Import ────────────────────────────────────────────────────────────────

const REQUIRED_CSV_HEADERS = ['full_name', 'student_id', 'email', 'faculty_code'];
// receipt_number is now OPTIONAL — system auto-generates an access PIN when absent

export async function importGraduates(req: Request, res: Response, next: NextFunction): Promise<void> {
  try {
    const { id: eventId } = req.params;

    // Verify event exists and is in a state that allows imports
    const eventRes = await query<EventRow>(`SELECT * FROM events WHERE id = $1`, [eventId]);
    const event = eventRes.rows[0];
    if (!event) throw new AppError(404, 'Event not found');
    if (['LIVE', 'CLOSED', 'ARCHIVED'].includes(event.status)) {
      throw new AppError(409, 'Cannot import graduates into an event that is LIVE, CLOSED, or ARCHIVED');
    }

    if (!req.file) throw new AppError(400, 'No CSV file uploaded');

    let rows: GraduateCsvRow[];
    try {
      rows = parse(req.file.buffer, {
        columns: true,
        skip_empty_lines: true,
        trim: true,
      }) as GraduateCsvRow[];
    } catch {
      throw new AppError(400, 'Invalid CSV format');
    }

    if (rows.length === 0) throw new AppError(400, 'CSV file is empty');

    // Validate headers
    const headers = Object.keys(rows[0] ?? {});
    const missing = REQUIRED_CSV_HEADERS.filter((h) => !headers.includes(h));
    if (missing.length > 0) {
      throw new AppError(400, `CSV missing required columns: ${missing.join(', ')}`);
    }

    // Load faculty map for this event (code → id, gate_id)
    const facultyRes = await query<FacultyRow & { gate_code: string }>(
      `SELECT f.id, f.code, f.gate_id, g.code AS gate_code
       FROM faculties f JOIN gates g ON g.id = f.gate_id
       WHERE f.event_id = $1`,
      [eventId]
    );
    const facultyMap = new Map(facultyRes.rows.map((f) => [f.code.toUpperCase(), f]));

    const summary: ImportSummary = { totalRows: rows.length, imported: 0, duplicates: 0, failed: 0, errors: [], generatedPins: [] };

    for (let i = 0; i < rows.length; i++) {
      const row = rows[i]!;
      const rowNum = i + 2; // 1-based, +1 for header

      // Field-level validation
      if (!row.full_name?.trim()) {
        summary.failed++;
        summary.errors.push({ row: rowNum, reason: 'Missing full_name' });
        continue;
      }
      if (!row.student_id?.trim()) {
        summary.failed++;
        summary.errors.push({ row: rowNum, reason: 'Missing student_id' });
        continue;
      }
      if (!row.email?.trim() || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(row.email)) {
        summary.failed++;
        summary.errors.push({ row: rowNum, reason: 'Invalid or missing email' });
        continue;
      }

      const faculty = facultyMap.get(row.faculty_code?.trim().toUpperCase());
      if (!faculty) {
        summary.failed++;
        summary.errors.push({ row: rowNum, reason: `Unknown faculty_code: ${row.faculty_code}` });
        continue;
      }

      // Check duplicate student_id within this event
      const dupCheck = await query(
        `SELECT id FROM graduates WHERE event_id = $1 AND student_id = $2`,
        [eventId, row.student_id.trim()]
      );
      if (dupCheck.rows.length > 0) {
        summary.duplicates++;
        summary.errors.push({ row: rowNum, reason: `Duplicate student_id: ${row.student_id}` });
        continue;
      }

      // Use receipt_number from CSV if provided, otherwise auto-generate a PIN
      const plainPin = row.receipt_number?.trim() || generatePin();
      const pinAutoGenerated = !row.receipt_number?.trim();
      const pinHash = await bcrypt.hash(plainPin, 10);

      try {
        const insertRes = await query<{ id: string }>(
          `INSERT INTO graduates
             (event_id, full_name, student_id, receipt_number_hash, email,
              faculty_id, department, phone)
           VALUES ($1,$2,$3,$4,$5,$6,$7,$8)
           RETURNING id`,
          [
            eventId,
            row.full_name.trim(),
            row.student_id.trim(),
            pinHash,
            row.email.trim().toLowerCase(),
            faculty.id,
            row.department?.trim() ?? null,
            row.phone?.trim() ?? null,
          ]
        );
        const newGraduateId = insertRes.rows[0]?.id ?? '';
        summary.imported++;

        // Track auto-generated PINs in the response (plaintext — returned once only)
        if (pinAutoGenerated) {
          summary.generatedPins.push({
            student_id: row.student_id.trim(),
            full_name:  row.full_name.trim(),
            pin:        plainPin,
          });
        }

        // Send credentials email (non-blocking — failures logged, not thrown)
        sendCredentials({
          graduateId: newGraduateId,
          to: row.email.trim().toLowerCase(),
          graduateName: row.full_name.trim(),
          studentId: row.student_id.trim(),
          accessPin: plainPin,
          eventName: event.name,
          eventDate: event.event_date,
          portalUrl: config.app.portalUrl,
          assignedGateCode: faculty.gate_code,
        }).catch(() => {/* already logged inside sendCredentials */});
      } catch {
        summary.failed++;
        summary.errors.push({ row: rowNum, reason: 'Database insert failed' });
      }
    }

    await logAudit({
      userId: req.admin!.sub,
      eventId,
      action: 'IMPORT_GRADUATES',
      targetId: eventId,
      targetType: 'event',
      details: { totalRows: summary.totalRows, imported: summary.imported, failed: summary.failed, pinsGenerated: summary.generatedPins.length },
      ipAddress: req.ip,
    });

    res.status(201).json({ ok: true, data: summary });
  } catch (err) {
    if (err instanceof z.ZodError) { next(new AppError(400, 'Validation error', err.issues)); return; }
    next(err);
  }
}

// ── List Graduates ────────────────────────────────────────────────────────────

export async function listGraduates(req: Request, res: Response, next: NextFunction): Promise<void> {
  try {
    const { id: eventId } = req.params;
    const page  = Math.max(1, parseInt(String(req.query.page  ?? 1), 10));
    const limit = Math.min(100, parseInt(String(req.query.limit ?? 50), 10));
    const offset = (page - 1) * limit;

    const [countRes, dataRes] = await Promise.all([
      query<{ count: string }>(
        `SELECT COUNT(*) FROM graduates WHERE event_id = $1`, [eventId]
      ),
      query<GraduateRow & { faculty_code: string; faculty_name: string; gate_code: string }>(
        `SELECT g.id, g.full_name, g.student_id, g.email, g.department, g.phone,
                g.credentials_sent_at, g.last_login_at, g.created_at,
                f.code AS faculty_code, f.name AS faculty_name,
                gt.code AS gate_code
         FROM graduates g
         JOIN faculties f ON f.id = g.faculty_id
         JOIN gates gt ON gt.id = f.gate_id
         WHERE g.event_id = $1
         ORDER BY g.full_name
         LIMIT $2 OFFSET $3`,
        [eventId, limit, offset]
      ),
    ]);

    res.json({
      ok: true,
      data: {
        graduates: dataRes.rows,
        total: parseInt(countRes.rows[0]?.count ?? '0', 10),
        page,
        limit,
      },
    });
  } catch (err) { next(err); }
}

// ── Get Graduate ──────────────────────────────────────────────────────────────

export async function getGraduate(req: Request, res: Response, next: NextFunction): Promise<void> {
  try {
    const { id: eventId, graduateId } = req.params;
    const result = await query<GraduateRow>(
      `SELECT id, full_name, student_id, email, department, phone,
              credentials_sent_at, last_login_at, created_at
       FROM graduates WHERE id = $1 AND event_id = $2`,
      [graduateId, eventId]
    );
    if (!result.rows[0]) throw new AppError(404, 'Graduate not found');
    res.json({ ok: true, data: result.rows[0] });
  } catch (err) { next(err); }
}

// ── Delete Graduate ───────────────────────────────────────────────────────────

export async function deleteGraduate(req: Request, res: Response, next: NextFunction): Promise<void> {
  try {
    const { id: eventId, graduateId } = req.params;

    const existing = await query<GraduateRow>(
      `SELECT full_name, student_id FROM graduates WHERE id = $1 AND event_id = $2`,
      [graduateId, eventId]
    );
    if (!existing.rows[0]) throw new AppError(404, 'Graduate not found');

    await withTransaction(async (client) => {
      await client.query(`DELETE FROM graduates WHERE id = $1`, [graduateId]);
      await logAudit({
        userId: req.admin!.sub,
        eventId,
        action: 'DELETE_GRADUATE',
        targetId: graduateId,
        targetType: 'graduate',
        details: { student_id: existing.rows[0]!.student_id, full_name: existing.rows[0]!.full_name },
        ipAddress: req.ip,
      }, client);
    });

    res.json({ ok: true, data: null });
  } catch (err) { next(err); }
}

// ── Reset PIN (single graduate) ───────────────────────────────────────────────
// Generates a new PIN, updates the hash, returns plaintext once.

export async function resetPin(req: Request, res: Response, next: NextFunction): Promise<void> {
  try {
    const { id: eventId, graduateId } = req.params;

    const gradRes = await query<GraduateRow>(
      `SELECT id, full_name, student_id FROM graduates WHERE id = $1 AND event_id = $2`,
      [graduateId, eventId]
    );
    const grad = gradRes.rows[0];
    if (!grad) throw new AppError(404, 'Graduate not found');

    const newPin  = generatePin();
    const newHash = await bcrypt.hash(newPin, 10);

    await query(
      `UPDATE graduates SET receipt_number_hash = $1, login_attempt_count = 0, locked_at = NULL WHERE id = $2`,
      [newHash, graduateId]
    );

    await logAudit({
      userId: req.admin!.sub,
      eventId,
      action: 'RESET_PIN',
      targetId: graduateId,
      targetType: 'graduate',
      details: { student_id: grad.student_id },
      ipAddress: req.ip,
    });

    res.json({ ok: true, data: { student_id: grad.student_id, full_name: grad.full_name, pin: newPin } });
  } catch (err) { next(err); }
}

// ── Bulk Reset Pins ───────────────────────────────────────────────────────────
// Regenerates PINs for all graduates who have NEVER logged in.
// Returns the full PIN list as JSON (admin should download immediately).
// Graduates who have already logged in are untouched.

export async function bulkResetPins(req: Request, res: Response, next: NextFunction): Promise<void> {
  try {
    const { id: eventId } = req.params;

    const gradRes = await query<{ id: string; student_id: string; full_name: string }>(
      `SELECT id, student_id, full_name FROM graduates
       WHERE event_id = $1 AND last_login_at IS NULL
       ORDER BY full_name`,
      [eventId]
    );

    const results: Array<{ student_id: string; full_name: string; pin: string }> = [];

    for (const grad of gradRes.rows) {
      const pin  = generatePin();
      const hash = await bcrypt.hash(pin, 10);
      await query(
        `UPDATE graduates SET receipt_number_hash = $1, login_attempt_count = 0, locked_at = NULL WHERE id = $2`,
        [hash, grad.id]
      );
      results.push({ student_id: grad.student_id, full_name: grad.full_name, pin });
    }

    await logAudit({
      userId: req.admin!.sub,
      eventId,
      action: 'BULK_RESET_PINS',
      targetId: eventId,
      targetType: 'event',
      details: { count: results.length },
      ipAddress: req.ip,
    });

    res.json({ ok: true, data: { count: results.length, pins: results } });
  } catch (err) { next(err); }
}

// ── Resend Credentials ────────────────────────────────────────────────────────
// Resets the PIN and emails the new one — the old PIN is invalidated.

export async function resendCredentials(req: Request, res: Response, next: NextFunction): Promise<void> {
  try {
    const { id: eventId, graduateId } = req.params;

    const gradRes = await query<GraduateRow & { faculty_code: string; gate_code: string; event_name: string; event_date: string }>(
      `SELECT g.*, f.code AS faculty_code, gt.code AS gate_code,
              e.name AS event_name, e.event_date::text AS event_date
       FROM graduates g
       JOIN faculties f ON f.id = g.faculty_id
       JOIN gates gt ON gt.id = f.gate_id
       JOIN events e ON e.id = g.event_id
       WHERE g.id = $1 AND g.event_id = $2`,
      [graduateId, eventId]
    );
    const grad = gradRes.rows[0];
    if (!grad) throw new AppError(404, 'Graduate not found');

    // Generate a fresh PIN — the old one is now invalid
    const newPin  = generatePin();
    const newHash = await bcrypt.hash(newPin, 10);
    await query(
      `UPDATE graduates SET receipt_number_hash = $1, login_attempt_count = 0, locked_at = NULL,
                            credentials_sent_at = NOW()
       WHERE id = $2`,
      [newHash, graduateId]
    );

    await sendCredentials({
      graduateId: grad.id,
      to: grad.email,
      graduateName: grad.full_name,
      studentId: grad.student_id,
      accessPin: newPin,
      eventName: grad.event_name,
      eventDate: grad.event_date,
      portalUrl: config.app.portalUrl,
      assignedGateCode: grad.gate_code,
    });

    await logAudit({
      userId: req.admin!.sub,
      eventId,
      action: 'RESEND_CREDENTIALS',
      targetId: graduateId,
      targetType: 'graduate',
      ipAddress: req.ip,
    });

    res.json({ ok: true, data: { message: 'New PIN generated and credentials email sent' } });
  } catch (err) { next(err); }
}
